Added OReadonlyEntity
JetBrains/xodus pull request #142
Opened 2024-04-24 13:07 UTC by leostryuk

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

### Checklist

[] I have added unit tests to the code I am submitting
[] My unit tests cover both failure and success scenarios
[] If applicable, I have discussed my architecture

2024-04-29 09:56 UTC, laa requested changes

2024-04-29 14:16 UTC, leostryuk commented
And so wee need to replace all usages of a snapshot to just using same entity in xodus-dnq

2024-04-29 14:31 UTC, vladimir-zatsepin commented on entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OReadonlyVertexEntity.kt
> +        throw IllegalArgumentException("Can't update readonly entity!")
Would add id into the log without exclamation mark, something like:
```suggestion
        throw IllegalArgumentException("Can't update readonly entity (id=${id})")
```

2024-04-30 07:22 UTC, laa approved these changes

2024-04-30 10:30 UTC, merged